;;; vtab-tests.el --- Tests for vtab -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'vtab)

(ert-deftest vtab-flat-tabs-keep-their-original-numbers ()
  (with-temp-buffer
    (vtab--insert-tabs '((1 "first" nil nil)
                         (2 "second" nil t)) nil)
    (should (equal (buffer-string) "  1: first\n> 2: second\n"))
    (should (= (get-text-property (point-min) 'vtab-index) 1))
    (should-not (get-text-property (point-min) 'vtab-group-header))))

(ert-deftest vtab-groups-tabs-without-changing-their-absolute-numbers ()
  (with-temp-buffer
    (vtab--insert-tabs '((1 "one" "A" nil)
                         (2 "other" nil nil)
                         (3 "two" "B" t)
                         (4 "three" "A" nil)) nil)
    (should (equal (buffer-string)
                   "▼ A\n    1: one\n    4: three\n▼ Other\n    2: other\n▼ B\n  > 3: two\n"))
    (goto-char (point-min))
    (should (get-text-property (point) 'vtab-group-header))
    (should (= (get-text-property (point) 'vtab-group-first-tab) 1))
    (should (eq (lookup-key (get-text-property (point) 'keymap) [mouse-1])
                #'vtab--click-toggle-group))
    (should (eq (lookup-key (get-text-property (+ (point) 2) 'keymap) [mouse-1])
                #'vtab--click-group))
    (search-forward "4: three")
    (should (= (get-text-property (1- (point)) 'vtab-index) 4))))

(ert-deftest vtab-current-row-follows-group-expansion ()
  (let ((tabs '((1 "one" "A" nil)
                (2 "two" "B" nil)
                (3 "three" "A" t))))
    (cl-letf (((symbol-function 'vtab--get-tabs) (lambda () tabs)))
      (with-temp-buffer
        (vtab--insert-tabs tabs nil)
        (should (= (get-text-property (vtab--current-row-position 2) 'vtab-index)
                   3))
        (erase-buffer)
        (vtab--insert-tabs tabs '("A"))
        (let ((row (vtab--current-row-position 2)))
          (should (get-text-property row 'vtab-group-header))
          (should (equal (get-text-property row 'vtab-group) "A")))))))

(ert-deftest vtab-group-toggle-and-select-use-frame-local-display-state ()
  (let ((frame (selected-frame))
        (old-state (frame-parameter nil 'vtab--tab-state))
        (old-collapsed (frame-parameter nil 'vtab--collapsed-groups))
        (old-buffer (frame-parameter nil 'vtab--buffer))
        selected)
    (unwind-protect
        (cl-letf (((symbol-function 'tab-bar-tabs)
                   (lambda (&optional _frame)
                     '((tab (name . "a") (group . "A"))
                       (tab (name . "b") (group . "A"))
                       (current-tab (name . "c") (group . "B")))))
                  ((symbol-function 'tab-bar-select-tab)
                   (lambda (index) (setq selected index))))
          (set-frame-parameter frame 'vtab--tab-state nil)
          (set-frame-parameter frame 'vtab--collapsed-groups nil)
          (vtab--refresh)
          (let ((buf (vtab--get-buffer)))
            (with-current-buffer buf
              (goto-char (point-min))
              (vtab--toggle-group)
              (should (equal (buffer-string)
                             "▶ A\n▼ B\n  > 3: c\n"))
              (should (equal (frame-parameter frame 'vtab--collapsed-groups)
                             '("A")))
              (forward-line 1)
              (vtab--toggle-group)
              (goto-char (point-min))
              (vtab--toggle-group)
              (should (equal (frame-parameter frame 'vtab--collapsed-groups)
                             '("B")))
              (should (equal (buffer-string)
                             "▼ A\n    1: a\n    2: b\n▶ B\n"))
              (vtab--select-group)
              (should (= selected 1))
              (should (equal (with-current-buffer buf (buffer-string))
                             "▼ A\n    1: a\n    2: b\n▶ B\n"))
              (should (equal (frame-parameter frame 'vtab--collapsed-groups)
                             '("B"))))))
      (let ((buf (frame-parameter frame 'vtab--buffer)))
        (unless (eq buf old-buffer)
          (when (buffer-live-p buf) (kill-buffer buf))))
      (set-frame-parameter frame 'vtab--buffer old-buffer)
      (set-frame-parameter frame 'vtab--tab-state old-state)
      (set-frame-parameter frame 'vtab--collapsed-groups old-collapsed))))

(ert-deftest vtab-refreshes-when-a-group-changes-or-an-inactive-group-closes ()
  (skip-unless (and (fboundp 'tab-bar-change-tab-group)
                    (fboundp 'tab-bar-close-group-tabs)))
  (let ((vtab-style-fringe nil)
        (vtab-style-window-divider nil)
        (frame (selected-frame))
        (saved-tabs (copy-tree (frame-parameter nil 'tabs)))
        (saved-current (copy-tree (frame-parameter nil 'current-tab))))
    (unwind-protect
        (progn
          (vtab-mode 1)
          (tab-bar-change-tab-group "A")
          (should (string-match-p "▼ A" (with-current-buffer (vtab--get-buffer)
                                           (buffer-string))))
          (tab-bar-new-tab)
          (tab-bar-change-tab-group "B")
          (tab-bar-select-tab 1)
          (tab-bar-close-group-tabs "B")
          ;; Simulate the post-command hook after an interactive command.
          (vtab--refresh-if-enabled)
          (should-not (string-match-p "▼ B" (with-current-buffer (vtab--get-buffer)
                                               (buffer-string)))))
      (vtab-mode -1)
      (set-frame-parameter frame 'tabs saved-tabs)
      (set-frame-parameter frame 'current-tab saved-current))))

(provide 'vtab-tests)

;;; vtab-tests.el ends here
